# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-05 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20200105_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='posted_by',
        ),
    ]
