# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 06:00
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20200106_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
